routes/web.php
<?php
Auth::routes();
Route::get('/', 'FrontendController@index');
Route::group(['prefix'=>'feposts'], function() {
  Route::get('category/{category}', 'FrontendController@category')->name('feposts.category');
  Route::get('tag/{tag}', 'FrontendController@tag')->name('feposts.tag');
  Route::get('user/{user}', 'FrontendController@user')->name('feposts.user');
  Route::post('search', 'FrontendController@search')->name('feposts.search');
  Route::post('subscribe', 'FrontendController@subscribe')->name('feposts.subscribe');
});
Route::resource('feposts', 'FrontendController')->only(['index', 'show']);
Route::group(['prefix'=>'admin'], function() {
  Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('posts/trashed', 'PostController@trashedIndex')->name('posts.trashed');
    Route::post('posts/{id}/restore', 'PostController@restorePost')->name('posts.restore');
    Route::delete('posts/{id}/permDelete', 'PostController@permDelete')->name('posts.permDelete');
    Route::post('users/{user}/admin', 'UserController@adminToggle')
      ->middleware('admin')->name('users.adminToggle');
    Route::get('profile/{user}', 'ProfileController@editProfile')->name('profile.editProfile');
    Route::put('profile/{user}', 'ProfileController@saveProfile')->name('profile.saveProfile');
    Route::resource('posts', 'PostController')->except(['show']);
    Route::resource('categories', 'CategoryController')->except(['create', 'show']);
    Route::resource('tags', 'TagController')->except(['create', 'show']);
    Route::resource('users', 'UserController')->except(['show', 'edit', 'update']);
    Route::get('settings/edit', 'SettingController@edit')->name('settings.edit');
    Route::put('settings/{settings}/update', 'SettingController@update')->name('settings.update');
  });
});

resources/views/admin/inc/footer.blade.php
<script
  src="http://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous">
</script>
<script src="{{asset('js/app.js')}}"></script>
@yield('scripts')

resources/views/admin/inc/head.blade.php
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{csrf_token()}}">
  <title>{{config('app.name', 'Laravel')}}</title>
  <link href="{{asset('css/app.css')}}" rel="stylesheet">
  <link href="{{asset('css/fa.min.css')}}" rel="stylesheet">
  @yield('styles')
</head>

resources/views/admin/inc/msg.blade.php
@if(count($errors)>0)
<div class="alert alert-danger">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <i class="fa fa-times-circle fa-lg" aria-hidden="true"></i>
  </button>
  @foreach($errors->all() as $err)
  <p><i class="fa fa-thumbs-o-down fa-lg"></i>&nbsp;&nbsp;{{$err}}</p>
  @endforeach
</div>
@endif

@if (session('success'))
<div class="alert alert-success">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <i class="fa fa-times-circle fa-lg" aria-hidden="true"></i>
  </button>
  <i class="fa fa-thumbs-o-up fa-lg">&nbsp;&nbsp;</i>{{session('success')}}
</div>
@endif

@if (session('error'))
<div class="alert alert-danger">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <i class="fa fa-times-circle fa-lg" aria-hidden="true"></i>
  </button>
  <i class="fa fa-thumbs-o-down fa-lg"></i>&nbsp;&nbsp;{{session('error')}}
</div>
@endif

@if (session('info'))
<div class="alert alert-info">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <i class="fa fa-times-circle fa-lg" aria-hidden="true"></i>
  </button>
  <i class="fa fa-hand-paper-o fa-lg"></i>&nbsp;&nbsp;{{session('info')}}
</div>
@endif

resources/views/admin/inc/nav.blade.php
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <!-- Collapsed Hamburger -->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{url('/')}}">{{config('app.name', 'Laravel')}}</a>
    </div>
    <div class="collapse navbar-collapse" id="app-navbar-collapse">
      <!-- Left Side Of Navbar -->
      <ul class="nav navbar-nav">&nbsp;</ul>
      <!-- Right Side Of Navbar -->
      <ul class="nav navbar-nav navbar-right">
        @guest
        <li><a href="{{route('login')}}">Login</a></li>
        <li><a href="{{route('register')}}">Register</a></li>
        @else
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            {{Auth::user()->name}} <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a href="{{route('logout')}}"
                 onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();">Logout
              </a>
              <form id="logout-form" action="{{route('logout')}}" method="POST" style="display: none;">
                {{csrf_field()}}
              </form>
            </li>
          </ul>
        </li>
        @endguest
      </ul>
    </div>
  </div>
</nav>

resources/views/admin/inc/sidebar.blade.php
<ul class="list-group">
  <li class="list-group-item"><a href="{{route('feposts.index')}}">Home Page</a></li>
  <li class="list-group-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
  <li class="list-group-item"><a href="{{route('profile.editProfile', auth()->user())}}">My Profile</a></li>
  <li class="list-group-item"><a href="{{route('posts.create')}}">Create Post</a></li>
  @if(auth()->user()->admin)
  <li class="list-group-item"><a href="{{route('posts.index')}}">Published Posts</a></li>
  <li class="list-group-item"><a href="{{route('posts.trashed')}}">Trashed Posts</a></li>
  <li class="list-group-item"><a href="{{route('categories.index')}}">Categories</a></li>
  <li class="list-group-item"><a href="{{route('tags.index')}}">Tags</a></li>
  <li class="list-group-item"><a href="{{route('users.index')}}">Active Users</a></li>
  <li class="list-group-item"><a href="{{route('users.create')}}">Create User</a></li>
  <li class="list-group-item"><a href="{{route('settings.edit')}}">Edit Settings</a></li>
  @endif
</ul>