routes/web.php
<?php
Auth::routes();
Route::get('/', 'FrontendController@index');
Route::group(['prefix'=>'feposts'], function() {
  Route::get('category/{category}', 'FrontendController@category')->name('feposts.category');
  Route::get('tag/{tag}', 'FrontendController@tag')->name('feposts.tag');
  Route::get('user/{user}', 'FrontendController@user')->name('feposts.user');
  Route::post('search', 'FrontendController@search')->name('feposts.search');
  Route::post('subscribe', 'FrontendController@subscribe')->name('feposts.subscribe');
});
Route::resource('feposts', 'FrontendController')->only(['index', 'show']);
Route::group(['prefix'=>'admin'], function() {
  Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('posts/trashed', 'PostController@trashedIndex')->name('posts.trashed');
    Route::post('posts/{id}/restore', 'PostController@restorePost')->name('posts.restore');
    Route::delete('posts/{id}/permDelete', 'PostController@permDelete')->name('posts.permDelete');
    Route::post('users/{user}/admin', 'UserController@adminToggle')
      ->middleware('admin')->name('users.adminToggle');
    Route::get('profile/{user}', 'ProfileController@editProfile')->name('profile.editProfile');
    Route::put('profile/{user}', 'ProfileController@saveProfile')->name('profile.saveProfile');
    Route::resource('posts', 'PostController')->except(['show']);
    Route::resource('categories', 'CategoryController')->except(['create', 'show']);
    Route::resource('tags', 'TagController')->except(['create', 'show']);
    Route::resource('users', 'UserController')->except(['show', 'edit', 'update']);
    Route::get('settings/edit', 'SettingController@edit')->name('settings.edit');
    Route::put('settings/{settings}/update', 'SettingController@update')->name('settings.update');
  });
});

app/Post.php
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\softDeletes;

class Post extends Model
{
  use softDeletes;
  protected $fillable = ['user_id', 'title', 'featured', 
                         'content', 'category_id', 'slug'];
  protected $dates    = ['deleted_at'];

  public function category()
  { return $this->belongsTo(Category::class); }

  public function tags()
  { return $this->belongsToMany(Tag::class); }

  public function user()
  { return $this->belongsTo(User::class); }

  // Image is stored as "public/uploads/posts/<filename>" in 
  // "storage/app" directory. But symbolic link is from 
  // "public/storage" to "storage/app/public", so the file for
  // the asset() function should be converted to 
  // "storage/uploads/posts/<filename>".
  public function getFeaturedAttribute($featured)
  { return str_replace_first('public', 'storage', $featured); }

  public function getTitleAttribute($title)
  { return title_case($title); }
}

app/Http/Controllers/API/PostController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Post;
use Illuminate\Support\Facades\Validator;
use Storage;
class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $post=Post::all();
        if($post==null){
            return response()->json([
                'isOk' => false,
                'message' => 'Post can not be Retrieved'
            ]); 
        }
        elseif($post->count()==0){
            return response()->json([
                'isOk' => true,
                'message' => 'No Post to Retrieve'
            ]);
        }
        else{
            return response()->json([
                'isOk' => true,
                'data' => $post
            ]);
        }
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $PostData = $request->all();
        $validator = Validator::make($PostData, [
            'title'       => 'required|max:100',
            'content'     => 'required',
            'category_id' => 'required'
        ]);
        
        if($validator->fails()){
            return response()->json(['isOk'=>false,'message' => $validator->errors()->first()]);
        }
        else{
        $user_id=auth()->id();
        $post= Post::create([
            'user_id'     => $user_id,
            'title'       => $request->title,
            'featured'    => "public/uploads/posts/$user_id.png",
            'content'     => $request->content,
            'category_id' => $request->category_id,
            'slug'        => str_slug($request->title)
       ]);
      
       $file = new \SplFileInfo(base_path('default-post.png'));
        Storage::putFileAs('public/uploads/posts', $file, "$user_id.png");
       
        if($post!=null)
        {
        
        return response()->json(['isOk' => true, 'Post' => $post]);
        }
        else{
            return response()->json([ 'isOk' => false, 'message' => 'Post has not created']);
        }
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
 
        if (!$post) {
            return response()->json([
                'isOk' => false,
                'message' => 'Post not found '
            ], 400);
        }
        else{
        return response()->json([
            'isOk' => true,
            'data' => $post->toArray()
        ], 200);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::find($id);
        if (!$post) {
            return response()->json([
                'isOk' => false,
                'message' => 'Post not found '
            ], 400);
        }
        else{
            $PostData = $request->all();
        $validator = Validator::make($PostData, [
            'title'       => 'required|max:100',
            'content'     => 'required',
            'category_id' => 'required'
        ]);
        
        if($validator->fails()){
            return response()->json(['isOk'=>false,'message' => $validator->errors()->first()]);
        }
        else{
        $user_id=auth()->id();
        $count= $post->Update([
            'user_id'     => auth()->id(),
            'title'       => $request->title,
            'featured'    => "public/uploads/posts/$user_id.png",
            'content'     => $request->content,
            'category_id' => $request->category_id,
            'slug'        => str_slug($request->title)
       ]);
        if($count!=0)
        {
        
        return response()->json(['isOk' => true,'message' => 'Post has Updated', 'Post' => $post]);
        }
        else{
            return response()->json([ 'isOk' => false, 'message' => 'Post has not Updated']);
        }
        }
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
 
        if (!$post) {
            return response()->json([
                'isOk' => false,
                'message' => 'Post not found'
            ], 400);
        }
 
        if ($post->delete()) {
            return response()->json([
                'isOk' => true,
                'message' => 'Post has deleted'
            ]);
        } else {
            return response()->json([
                'isOk' => false,
                'message' => 'Post can not be deleted'
            ], 500);
        }
    }
}

app/Http/Controllers/PostController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Post;
use App\Category;
use App\Tag;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
  public function index()
  {
    if($c = request()['cat']) {
      $cat = Category::find($c);
      $posts = $cat->posts()->latest()->paginate(10);
      $heading = " in category << $cat->name >>";
      $type = ['cat' => $cat->id];
    } elseif($t = request()['tag']) {
      $tag = Tag::find($t);
      $posts = $tag->posts()->latest()->paginate(10);
      $heading = " with tag << $tag->tag >>";
      $type = ['tag' => $tag->id];
    } else {
      $posts = Post::latest()->paginate(10);
      $heading = '';
      $type = [];
    }
     return view('admin.posts.index', compact('posts', 'heading', 'type'));
  }

  public function create()
  {
    $categories = Category::orderBy('name')->get();
    $tags = Tag::orderBy('tag')->get();
    if($categories->count() == 0) {
      return redirect()->route('categories.create')
                       ->with(['info' => 'Please create some categories first.']);
    } else {
      return view('admin.posts.create', compact('categories', 'tags'));
    }
  }

  public function store(Request $request)
  {
    $this->validate($request, [
      'title'       => 'required|max:100',
      'featured'    => 'required|image',
      'content'     => 'required',
      'category_id' => 'required'
    ]);
    $featured = $request->featured;
    // Append timestamp to filename to avoid duplicate names
    $img_name = time().$featured->getClientOriginalName();
    // Copy file to "storage/app/public/uploads/posts" folder
    $path = $request->file('featured')->storeAs('public/uploads/posts', $img_name);
    $post = Post::create([
      'user_id'     => auth()->id(),
      'title'       => $request->title,
      'featured'    => $path,
      'content'     => $request->content,
      'category_id' => $request->category_id,
      'slug'        => str_slug($request->title)
    ]);
    $post->tags()->attach($request->tags);
    return redirect()->route('posts.index')
                     ->with(['success' => 'Post successfully created.']);
  }

  public function edit(Post $post)
  {
    $categories = Category::all();
    $tags = Tag::orderBy('tag')->get();
    return view('admin.posts.edit', compact('post', 'categories', 'tags'));
  }

  public function update(Request $request, Post $post)
  {
    $this->validate($request, [
      'title'    => 'required|max:100',
      'content'  => 'required'
    ]);
    if($request->hasFile('featured')) {
      $old_img = str_replace_first('storage', 'public', $post->featured);
      Storage::delete($old_img);
      $featured = $request->featured;
      $img_name = time().$featured->getClientOriginalName();
      $path = $request->file('featured')->storeAs('public/uploads/posts', $img_name);
      $post->featured = $path;
    }
    $post->title = $request->title;
    $post->content = $request->content;
    $post->category_id = $request->category_id;
    $post->save();
    $post->tags()->sync($request->tags);
    return redirect()->route('posts.index')
                     ->with(['success' => 'Post successfully updated.']);
  }

  public function destroy(Post $post)
  {
    $post->delete();  // softDelete
    return redirect()->route('posts.index')
                     ->with(['success' => 'Post successfully trashed.']);
  }

  public function trashedIndex() 
  {
    $tPosts = Post::onlyTrashed()->orderBy('deleted_at', 'desc')->get();
    return view('admin.posts.trashed', compact('tPosts'));
  }

  public function restorePost($id)
  {
    $post = Post::onlyTrashed()->where('id', $id);
    $post->restore();
    return redirect()->route('posts.index')
                     ->with(['success' => 'Post successfully restored.']);
  }

  public function permDelete($id)
  {
    $post = Post::onlyTrashed()->find($id);
    $old_img = str_replace_first('storage', 'public', $post->featured);
    Storage::delete($old_img);
    $post->forceDelete();
    return redirect()->route('posts.trashed')
                     ->with(['success' => 'Post permanently deleted.']);
  }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.app')

@section('styles')
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
@endsection

@section('content')
<div class="panel panel-default">
  <div class="panel-heading">Create Post</div>
  <div class="panel-body">
    <form action="{{route('posts.store')}}" method="post" enctype="multipart/form-data">
      {{csrf_field()}}
      <div class="form-group">
        <label for="title">Title</label>
        <input type="text" name="title" class="form-control" value="{{old('title')}}">
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="featured">Featured Image</label>
            <input type="file" name="featured" class="form-control" value="{{old('featured')}}">
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="category">Category</label>
            <select class="form-control" name="category_id">
              @foreach($categories as $cat)
              <option value="{{$cat->id}}">{{$cat->name}}</option>
              @endforeach
            </select>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="tags">Select Tags</label>
        <div class="well well-sm">
        @if($tags->count() > 0)
        <?php
          $tagTotal = $tags->count();
          $n = 1;
        ?>
          @foreach($tags as $tag)
            @if($n % 4 == 1)
            <div class="row">
            @endif
              <div class="col-md-3">
                <label><input type="checkbox" name="tags[]" value="{{$tag->id}}">&nbsp;&nbsp;{{$tag->tag}}</label>
              </div>
            @if($n % 4 == 0 || $n == $tagTotal)
            </div>
            @endif
            <?php $n++; ?>
          @endforeach
        @else
        <a href="{{route('tags.index')}}" class="btn btn-success btn-xs">
          <i class="fa fa-tags"></i>&nbsp;&nbsp;Create Tags
        </a>
        @endif
        </div>
      </div>
      <div class="form-group">
        <label for="content">Content</label>
        <textarea id="summernote" name="content" class="form-control" value="{{old('content')}}"></textarea>
      </div>
      <button type="submit" name="button" class="btn btn-success">Create Post</button>
    </form>
  </div>
</div>
@endsection

@section('scripts')
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
      $('#summernote').summernote({height:150});
  });
</script>
@endsection

resources/views/admin/posts/edit.blade.php
@extends('layouts.app')

@section('styles')
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
@endsection

@section('content')
<div class="panel panel-default">
  <div class="panel-heading">Edit Post</div>
  <div class="panel-body">
    <form action="{{route('posts.update', $post)}}" method="post" enctype="multipart/form-data">
      {{csrf_field()}}
      {{method_field('put')}}
      <div class="form-group">
        <img src="{{asset($post->featured)}}" height="42" width="28 "alt="{{$post->title}}">
      </div>
      <div class="form-group">
        <label for="title">Title</label>
        <input type="text" name="title" class="form-control" value="{{$post->title}}">
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="featured">New Featured Image</label>
            <input type="file" name="featured" class="form-control" value="{{$post->featured}}">
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="category">Category</label>
            <select class="form-control" name="category_id">
              @foreach($categories as $cat)
              <option value="{{$cat->id}}"
                {{$post->category_id == $cat->id ? 'selected' : ''}}>{{$cat->name}}</option>
              @endforeach
            </select>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="tags">Select Tags</label>
        <div class="well well-sm">
        @if($tags->count() > 0)
        <?php
          $tagTotal = $tags->count();
          $n = 1;
        ?>
          @foreach($tags as $tag)
            @if($n % 4 == 1)
            <div class="row">
            @endif
              <div class="col-md-3">
                <label><input type="checkbox" name="tags[]" value="{{$tag->id}}"
                   {{$post->tags->find($tag->id) ? 'checked' : ''}}>&nbsp;&nbsp;{{$tag->tag}}</label>
              </div>
            @if($n % 4 == 0 || $n == $tagTotal)
            </div>
            @endif
            <?php $n++; ?>
          @endforeach
        @else
        <a href="{{route('tags.index')}}" class="btn btn-success btn-xs">
          <i class="fa fa-tags"></i>&nbsp;&nbsp;Create Tags
        </a>
        @endif
        </div>
      </div>
      <div class="form-group">
        <label for="content">Content</label>
        <textarea id="summernote" name="content" class="form-control">{{$post->content}}</textarea>
      </div>
      <button type="submit" name="button" class="btn btn-success">Update Post</button>
    </form>
  </div>
</div>
@endsection

@section('scripts')
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    $('#summernote').summernote({height:150});
  });
</script>
@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="panel panel-default">
  <div class="panel-heading">Published Posts{{$heading}}</div>
  <div class="panel-body">
    @if($posts->count() > 0)
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Image</th>
          <th>Title</th>
          <th>Author</th>
          <th style="text-align:center">Edit</th>
          <th style="text-align:center">Delete?</th>
        </tr>
      </thead>
      <tbody>
        @foreach($posts as $post)
        <tr>
          <td><img src="{{asset($post->featured)}}" height="42" width="28 "alt="{{$post->title}}"></td>
          <td style="padding-top:15px">{{str_limit($post->title, 40)}}</td>
          <td style="padding-top:15px">{{$post->user->name}}</td>
          <td style="padding-top:15px;text-align:center">
            <a href="{{route('posts.edit', $post)}}" class="btn btn-info btn-xs">
              <i class="fa fa-pencil"></i>&nbsp;&nbsp;Edit
            </a>
          </td>
          <td style="padding-top:15px;text-align:center">
            <form action="{{route('posts.destroy', $post)}}" method="post">
              {{csrf_field()}}
              {{method_field('delete')}}
              <button type="submit" id="del-btn" name="button" class="btn btn-danger btn-xs">
                <i class="fa fa-trash"></i>&nbsp;&nbsp;Trash
              </button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    @if(array_has($type, 'cat'))
    {{$posts->appends(['cat'=>$type['cat']])->links()}}
    @elseif(array_has($type, 'tag'))
    {{$posts->appends(['tag'=>$type['tag']])->links()}}
    @else
    {{$posts->links()}}
    @endif
    @else
    <h3>There are no posts.</h3>
    @endif
  </div>
</div>
@endsection

resources/views/admin/posts/trashed.blade.php
@extends('layouts.app')

@section('content')
<div class="panel panel-default">
  <div class="panel-heading">Trashed Posts ({{$tPosts->count()}})</div>
  <div class="panel-body">
    @if($tPosts->count() > 0)
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Image</th>
          <th>Title</th>
          <th>Restore?</th>
          <th>Permanently Delete?</th>
        </tr>
      </thead>
      <tbody>
        @foreach($tPosts as $tPost)
        <tr>
          <td><img src="{{asset($tPost->featured)}}" height="42" width="28" alt="{{$tPost->title}}"></td>
          <td>{{$tPost->title}}</td>
          <td>
            <form action="{{route('posts.restore', $tPost->id)}}" method="post">
              {{csrf_field()}}
              <button type="submit" name="button" class="btn btn-info btn-xs">
                <i class="fa fa-undo"></i>&nbsp;&nbsp;Restore
              </button>
            </form>
          </td>
          <td>
            <form action="{{route('posts.permDelete', $tPost->id)}}" method="post" onSubmit="return confirm('Are you sure?');">
              {{csrf_field()}}
              {{method_field('delete')}}
              <button type="submit" id="del-btn" name="button" class="btn btn-danger btn-xs">
                <i class="fa fa-trash"></i>&nbsp;&nbsp;Delete
              </button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    @else
    <h3>There are no trashed posts.</h3>
    @endif
  </div>
</div>
@endsection