routes/web.php
<?php
Auth::routes();
Route::get('/', 'FrontendController@index');
Route::group(['prefix'=>'feposts'], function() {
  Route::get('category/{category}', 'FrontendController@category')->name('feposts.category');
  Route::get('tag/{tag}', 'FrontendController@tag')->name('feposts.tag');
  Route::get('user/{user}', 'FrontendController@user')->name('feposts.user');
  Route::post('search', 'FrontendController@search')->name('feposts.search');
  Route::post('subscribe', 'FrontendController@subscribe')->name('feposts.subscribe');
});
Route::resource('feposts', 'FrontendController')->only(['index', 'show']);
Route::group(['prefix'=>'admin'], function() {
  Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('posts/trashed', 'PostController@trashedIndex')->name('posts.trashed');
    Route::post('posts/{id}/restore', 'PostController@restorePost')->name('posts.restore');
    Route::delete('posts/{id}/permDelete', 'PostController@permDelete')->name('posts.permDelete');
    Route::post('users/{user}/admin', 'UserController@adminToggle')
      ->middleware('admin')->name('users.adminToggle');
    Route::get('profile/{user}', 'ProfileController@editProfile')->name('profile.editProfile');
    Route::put('profile/{user}', 'ProfileController@saveProfile')->name('profile.saveProfile');
    Route::resource('posts', 'PostController')->except(['show']);
    Route::resource('categories', 'CategoryController')->except(['create', 'show']);
    Route::resource('tags', 'TagController')->except(['create', 'show']);
    Route::resource('users', 'UserController')->except(['show', 'edit', 'update']);
    Route::get('settings/edit', 'SettingController@edit')->name('settings.edit');
    Route::put('settings/{settings}/update', 'SettingController@update')->name('settings.update');
  });
});

app/Category.php
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
  protected $fillable = ['name'];

  public function posts() {
    return $this->hasMany(Post::class);
  }
}

app/Http/Controllers/CategoryController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Category;

class CategoryController extends Controller
{
  public function __construct()
  { $this->middleware('admin'); }

  public function index()
  {
    $categories = Category::orderBy('name')->get();
    return view('admin.categories.index', compact('categories'));
  }

  public function store(Request $request)
  {
    $this->validate($request, [
      'name' => 'required|min:3'
    ]);
    Category::create([ 'name' => $request->name ]);
    return redirect()->route('categories.index')
                     ->with(['success' => 'Category successfully created.']);
  }

  public function edit(Category $category)
  { return view('admin.categories.edit', compact('category')); }

  public function update(Request $request, Category $category)
  {
    $this->validate($request, [
      'name' => 'required|min:3'
    ]);
    $category->update(['name' => $request->name]);
    return redirect()->route('categories.index')
                     ->with(['success' => 'Category successfully updated!']);
  }

  public function destroy(Category $category)
  {
    if($category->posts->count() > 0) {
      return back()->with([
        'error' => 'Delete failed. There are posts in the "'.$category->name.'" category.']);
    } else {
      $category->delete();
      return redirect()->route('categories.index')
                       ->with(['success' => 'Category successfully deleted!']);
    }
  }
}

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="panel panel-default">
  <div class="panel-heading">Edit the "{{$category->name}}" Category</div>
  <div class="panel-body">
    <form action="{{route('categories.update', $category)}}" method="post">
      {{csrf_field()}}
      {{method_field('put')}}
      <div class="form-group">
        <label for="title">New Name</label>
        <input type="text" name="name" class="form-control" value="{{$category->name}}">
      </div>
      <button type="submit" name="button" class="btn btn-success">Update Category</button>
    </form>
  </div>
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')
<div class="panel panel-default">
  <div class="panel-heading">Categories ({{$categories->count()}})</div>
  <div class="panel-body">
    <form action="{{route('categories.store')}}" method="post">
      {{csrf_field()}}
      <div class="form-group">
        <label for="category">Category</label>
        <input type="text" name="name" class="form-control" autofocus>
      </div>
      <button type="submit" name="button" class="btn btn-success">Create Category</button>
    </form>
    <hr>
    @if($categories->count() > 0)
    <table class="table table-condensed table-hover">
      <thead>
        <tr>
          <th>Category Name</th>
          <th>Posts</th>
          <th>Show?</th>
          <th>Edit?</th>
          <th>Delete?</th>
        </tr>
      </thead>
      <tbody>
        @foreach($categories as $cat)
        <tr>
          <td>{{$cat->name}}</td>
          <td>{{$cat->posts->count()}}</td>
          <td>
            <a href="{{route('posts.index', ['cat' => $cat->id])}}" class="btn btn-primary btn-xs">
              <i class="fa fa-files-o"></i>&nbsp;&nbsp;Show
            </a>
          </td>          
          <td>
            <a href="{{route('categories.edit', $cat)}}" class="btn btn-success btn-xs">
              <i class="fa fa-pencil"></i>&nbsp;&nbsp;Edit
            </a>
          </td>
          <td>
            <form action="{{route('categories.destroy', $cat)}}" method="post" onSubmit="return confirm('Are you sure?');">
              {{csrf_field()}}
              {{method_field('delete')}}
              <button type="submit" id="del-btn" name="button" class="btn btn-danger btn-xs">
                <i class="fa fa-trash"></i>&nbsp;&nbsp;Delete
              </button>
            </form>
            </a>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    @else
    <h3>There are no categories.</h3>
    @endif
  </div>
</div>
@endsection