routes/web.php
<?php
Auth::routes();
Route::get('/', 'FrontendController@index');
Route::group(['prefix'=>'feposts'], function() {
  Route::get('category/{category}', 'FrontendController@category')->name('feposts.category');
  Route::get('tag/{tag}', 'FrontendController@tag')->name('feposts.tag');
  Route::get('user/{user}', 'FrontendController@user')->name('feposts.user');
  Route::post('search', 'FrontendController@search')->name('feposts.search');
  Route::post('subscribe', 'FrontendController@subscribe')->name('feposts.subscribe');
});
Route::resource('feposts', 'FrontendController')->only(['index', 'show']);
Route::group(['prefix'=>'admin'], function() {
  Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('posts/trashed', 'PostController@trashedIndex')->name('posts.trashed');
    Route::post('posts/{id}/restore', 'PostController@restorePost')->name('posts.restore');
    Route::delete('posts/{id}/permDelete', 'PostController@permDelete')->name('posts.permDelete');
    Route::post('users/{user}/admin', 'UserController@adminToggle')
      ->middleware('admin')->name('users.adminToggle');
    Route::get('profile/{user}', 'ProfileController@editProfile')->name('profile.editProfile');
    Route::put('profile/{user}', 'ProfileController@saveProfile')->name('profile.saveProfile');
    Route::resource('posts', 'PostController')->except(['show']);
    Route::resource('categories', 'CategoryController')->except(['create', 'show']);
    Route::resource('tags', 'TagController')->except(['create', 'show']);
    Route::resource('users', 'UserController')->except(['show', 'edit', 'update']);
    Route::get('settings/edit', 'SettingController@edit')->name('settings.edit');
    Route::put('settings/{settings}/update', 'SettingController@update')->name('settings.update');
  });
});

app/Tag.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
  protected $fillable = ['tag'];

  public function posts()
  { return $this->belongsToMany(Post::class); }
}

app/Http/Controllers/TagController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Tag;

class TagController extends Controller
{
  public function __construct()
  { $this->middleware('admin'); }

  public function index()
  {
    $tags = Tag::orderBy('tag')->get();
    return view('admin.tags.index', compact('tags'));
  }

  public function store(Request $request)
  {
    $this->validate($request, ['tag' => 'required:min3']);
    Tag::create(['tag' => $request->tag]);
    return redirect()->route('tags.index')
                     ->with(['success' => 'Tag successfully created.']);
  }

  public function edit(Tag $tag)
  { return view('admin.tags.edit', compact('tag')); }

  public function update(Request $request, Tag $tag)
  {
    $this->validate($request, ['tag' => 'required|min:3']);
    $tag->tag = $request->tag;
    $tag->save();
    return redirect()->route('tags.index')
                     ->with(['success' => 'Tag successfully updated.']);
  }

  public function destroy(Tag $tag)
  {
    $tag->posts()->detach();
    $tag->delete();
    return redirect()->back()
                     ->with(['success' => 'Tag successfully deleted.']);
  }
}

resources/views/admin/tags/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="panel panel-default">
  <div class="panel-heading">Edit the "{{$tag->tag}}" Tag</div>
  <div class="panel-body">
    <form action="{{route('tags.update', $tag)}}" method="post">
      {{csrf_field()}}
      {{method_field('put')}}
      <div class="form-group">
        <label for="tag">New Tag</label>
        <input type="text" name="tag" class="form-control" value="{{$tag->tag}}">
      </div>
      <button type="submit" name="button" class="btn btn-success">Update Tag</button>
    </form>
  </div>
</div>
@endsection

resources/views/admin/tags/index.blade.php
@extends('layouts.app')

@section('content')
<div class="panel panel-default">
  <div class="panel-heading">Tags ({{$tags->count()}})</div>
  <div class="panel-body">
    <form action="{{route('tags.store')}}" method="post">
      {{csrf_field()}}
      <div class="form-group">
        <label for="tag">Tag</label>
        <input type="text" name="tag" class="form-control" autofocus>
      </div>
      <button type="submit" name="button" class="btn btn-success">Create Tag</button>
    </form>
    <hr>
    @if($tags->count() > 0)
    <table class="table table-condensed table-hover">
      <thead>
        <tr>
          <th>Tag Name</th>
          <th>Posts</th>
          <th>Show?</th>
          <th>Edit?</th>
          <th>Delete?</th>
        </tr>
      </thead>
      <tbody>
        @foreach($tags as $tag)
        <tr>
          <td>{{$tag->tag}}</td>
          <td>{{$tag->posts->count()}}</td>
          <td>
            <a href="{{route('posts.index', ['tag' => $tag->id])}}" class="btn btn-primary btn-xs">
              <i class="fa fa-files-o"></i>&nbsp;&nbsp;Show
            </a>
          </td>          
          <td>
            <a href="{{route('tags.edit', $tag)}}" class="btn btn-success btn-xs">
              <i class="fa fa-pencil"></i>&nbsp;&nbsp;Edit
            </a>
          </td>
          <td>
            <form action="{{route('tags.destroy', $tag)}}" method="post" onSubmit="return confirm('Are you sure?');">
              {{csrf_field()}}
              {{method_field('delete')}}
              <button type="submit" id="del-btn" name="button" class="btn btn-danger btn-xs">
                <i class="fa fa-trash"></i>&nbsp;&nbsp;Delete
              </button>
            </form>
            </a>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    @else
    <h3>There are no tags.</h3>
    @endif
  </div>
</div>
@endsection